### ISSUE TITLE
This library is not working in IOS?

### ISSUE THREAD

**Issue by shubham1164** [francisco-sanchez-molina/react-native-store-photos-album#7]
**Using:** 
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
     "react-native-store-photos-album": "github:francisco-sanchez-molina/react-native-store-photos-album",

Xcode version: 10

**Issue:**
This library is working awesome with Android. But on IOS the App just crashes. I have installed and linked the library as described in the readme file. While looking at the IOS code in Xcode. I observed that this library is not linked and when I tried to link it, react-native-store-photos-album xcode proj is unselectable. Do you the reason. You library is really helpful if it works with IOS also. Thanks

![screenshot 2019-01-15 at 10 54 33 am](https://user-images.githubusercontent.com/14908473/51160540-650c5e00-18b4-11e9-964e-3f421ace80f5.png)

**Comment by shubham1164** [comment]
I just rebuild the project then its working fine

**Comment by Piyush132000** [comment]
hey please help please drop your saving code please
